# Generated by Django 3.1.6 on 2021-02-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
